# docker-compose.yml
version: '3'
services:
  db:
    image: postgres
    container_name: rails_sameple_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5439:5432"
    networks:
      - myapp_network

  pgadmin:
    container_name: rails_sameple_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5088:80"
    depends_on:
      - db
    networks:
      - myapp_network

  web:
    build: .
    container_name: rails_sameple_web
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/www
    ports:
      - "3002:3000"
    depends_on:
      - db
    networks:
      - myapp_network

volumes:
  db_data:
  pgadmin:

networks:
  myapp_network:
